Toast - fix typings
wix/react-native-ui-lib pull request #1333
Opened 2021-06-02 12:00 UTC by M-i-k-e-l

## Description
Toast - fix typings

## Changelog
Toast - fix typings

Resolves #1249

2021-06-02 12:51 UTC, lidord-wix requested changes

2021-06-02 12:51 UTC, lidord-wix commented on typings/components/Toast.d.ts
> -  actions?: ReadonlyArray<ButtonProps>;
`action` prop is missing

2021-06-02 12:51 UTC, lidord-wix commented on typings/components/Toast.d.ts
>    backgroundColor?: ColorValue;
`height` prop is unused :)

2021-06-03 07:58 UTC, M-i-k-e-l commented on typings/components/Toast.d.ts
> -  actions?: ReadonlyArray<ButtonProps>;
Fixed

2021-06-03 07:58 UTC, M-i-k-e-l commented on typings/components/Toast.d.ts
>    backgroundColor?: ColorValue;
Fixed

2021-06-03 08:20 UTC, lidord-wix commented on typings/components/Toast.d.ts
> +  actions?: ButtonProps;
Should be `action`, no?

2021-06-03 08:25 UTC, M-i-k-e-l commented on typings/components/Toast.d.ts
> +  actions?: ButtonProps;
Oops, fixed

2021-06-03 09:14 UTC, lidord-wix approved these changes

2021-06-03 09:14 UTC, merged