Fix/ renderSliderOption method
wix/react-native-ui-lib pull request #1381
Opened 2021-07-01 14:27 UTC by lidord-wix

## Description
Fix renderSliderOption function - fixes broken slider in few screens.
WOAUILIB-1907

## Changelog
Fix renderSliderOption function - fixes broken slider in few screens.

2021-07-28 08:03 UTC, Inbal-Tish requested changes

2021-08-01 08:53 UTC, lidord-wix commented on demo/src/screens/ExampleScreenPresenter.js
> +    width: 30
Because the slider width depends on the text width and should be constant

2021-08-01 08:57 UTC, lidord-wix commented on demo/src/screens/ExampleScreenPresenter.js
> +          {value || initial}
When there is no value passed

2021-08-01 08:59 UTC, Inbal-Tish commented on demo/src/screens/ExampleScreenPresenter.js
> +          {value || initial}
Look at line #110

2021-08-01 09:17 UTC, lidord-wix commented on demo/src/screens/ExampleScreenPresenter.js
> +          {value || initial}
Look at my last commit - is this what you meant?

2021-08-01 09:22 UTC, Inbal-Tish approved these changes

2021-08-01 10:00 UTC, merged