Migrate Slider, GradientSlider and ColorSliderGroup components to TypeScript.
wix/react-native-ui-lib pull request #1408
Opened 2021-07-15 13:16 UTC by saulve

## Description
This PR migrates the aforementioned components to TS with minor improvements. 

## Changelog
Migrated Slider context files
Deleted Slider.d.ts
Added default color prop for `GradientSlider` (the `color` prop is optional, however when it's not provided the slider component crashes.)

2021-07-15 13:17 UTC, saulve commented on src/components/colorPicker/ColorPickerDialog.tsx
> -//@ts-expect-error
This shows as an error in TS compile, however I don't see a reason for it, so I removed it.

2021-07-15 13:20 UTC, saulve commented on src/components/slider/ColorSliderGroup.tsx
> +   accessible?: boolean;
added `accessible` prop to toggle accessibility

2021-07-15 13:22 UTC, saulve commented on src/components/slider/GradientSlider.tsx
> +   accessible?: boolean;
added `accessible`, `containerStyle`, and `disabled` prop definitions.

2021-07-15 13:23 UTC, saulve commented on src/components/slider/GradientSlider.tsx
> -      color: props.color ? Colors.getHSL(props.color) : undefined
Leaving `this.state.color` undefined causes this component crash.  Added color in `defaultProps` to prevent this.

2021-07-15 13:26 UTC, saulve commented on src/components/slider/index.tsx
> +   accessible?: boolean;
added `accessible` prop type definition here

2021-07-15 15:48 UTC, saulve commented on typings/globalTypes.d.ts
> +declare module 'react-native-color' {
Not sure where non-typed js dependencies are declared, so I've added these dependencies here. Is this the right place?

2021-07-29 07:10 UTC, ethanshar commented
@mendyEdri 
Can you please take a look, it's been waiting for some time..

2021-07-29 10:57 UTC, mendyEdri commented on src/components/slider/ColorSliderGroup.tsx
> + * @example: https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/SliderScreen.js
```suggestion
 * @example: https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/SliderScreen.tsx
```

2021-07-29 10:57 UTC, mendyEdri commented on src/components/slider/GradientSlider.tsx
> + * @example: https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/SliderScreen.js
```suggestion
 * @example: https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/SliderScreen.tsx
```

2021-07-29 11:52 UTC, mendyEdri requested changes
Great. I think just the docs need to point the `.jsx` files

2021-08-02 08:34 UTC, saulve commented
@mendyEdri good catch. I've changed the example to point to tsx files

2021-08-02 08:58 UTC, mendyEdri approved these changes

2021-08-03 05:47 UTC, ethanshar commented
I think the CI here is stuck for some reason..
I merged PR with master to trigger another CI build, let's see how it goes..

2021-08-04 06:16 UTC, saulve commented
@ethanshar seems to be still stuck

2021-08-04 08:40 UTC, ethanshar commented
> @ethanshar seems to be still stuck

Yes, I wrote in mobile-oss-ci channel

2021-08-05 07:24 UTC, merged