Support multiple validators to Incubator.TextField
wix/react-native-ui-lib pull request #927
Opened 2020-09-07 10:25 UTC by ethanshar

2020-09-08 11:39 UTC, mendyEdri requested changes

2020-09-13 05:26 UTC, ethanshar commented on src/incubator/TextField/Presenter.ts
> +): [boolean, number | undefined] {
Fixed

2020-09-13 05:26 UTC, ethanshar commented on src/incubator/TextField/types.ts
> +export type Validator = Function | keyof typeof formValidators;
Fixed

2020-09-15 07:35 UTC, mendyEdri approved these changes

2020-09-15 07:35 UTC, merged